# Generated by Django 3.0.4 on 2020-03-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0002_auto_20200325_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportion',
            name='eating',
            field=models.IntegerField(choices=[(1, 'Завтрак'), (2, 'Обед'), (3, 'Ужин'), (4, 'Перекус')], default=4),
        ),
    ]
