# Generated by Django 3.0.4 on 2020-03-25 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0003_userportion_eating'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycalories',
            name='added_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daycalories',
            name='day',
            field=models.DateField(),
        ),
    ]
