# Generated by Django 3.0.4 on 2020-03-25 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0004_auto_20200325_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportion',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
