# Generated by Django 3.0.4 on 2021-12-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0007_auto_20211209_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userweight',
            name='day',
        ),
    ]
